---
- name: Install Argo CD on Raspberry Pi
  hosts: raspberry-pi
  become: true

  tasks:
    - name: Create Argo CD namespace
      ansible.builtin.command:
        cmd: "kubectl create namespace argocd"
        creates: "/etc/kubernetes/manifests/argocd"

    - name: Apply Argo CD manifests
      ansible.builtin.command:
        cmd: "kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
      args:
        executable: "/bin/sh"

