---
- hosts: raspberry-pi
  become: true
  become_user: root
  tasks:
    - name: Create namespaces for ArgoCD
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: mw
        state: present
