- name: Raspberry Pi Setup
  hosts: raspberrypi
  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - git
        - htop

