---
- name: Install k3s on Raspberry Pi
  hosts: masters
  become: true

  tasks:
    - name: Install k3s
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{k3s_version}} sh -s - --write-kubeconfig-mode 644
    - name: Fetch K3s token
      command: "sudo cat /var/lib/rancher/k3s/server/node-token"
      register: k3s_token
      become_user: root
    - name: Set K3s token as a fact
      ansible.builtin.set_fact:
        cluster_token: '{{ k3s_token.stdout }}'

- name: Install K3s on worker
  hosts: workers
  become: true
  tasks:
    - name: Install K3s on worker
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{k3s_version}} K3S_URL=https://{{master_ip}}:6443 K3S_TOKEN="{{ hostvars['pi5-m1']['k3s_token'].stdout }}" sh -

- name: Move Kube Config
  hosts: masters, workers
  become: true
  tasks:
    - name: Move kube config
      ansible.builtin.command:
        cmd: "cp /etc/rancher/k3s/k3s.yaml ~/.kube/config"