---
- name: Install k3s on Raspberry Pi
  hosts: raspberry-pi
  become: true

  tasks:
    - name: Install k3s
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.26.11+k3s2 sh -s - --write-kubeconfig-mode 644
    - name: Copy k3s.yaml
      ansible.builtin.command:
        cmd: "cp /etc/rancher/k3s/k3s.yaml ~/.kube/config"

