---
- name: Raspberry Pi OS Setup
  hosts: masters, workers
  become: true
  become_user: root
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
    - name: Install required packages
      apt:
        name:
          - iputils-ping
          - git
          - iptables
        state: present
    - name: Enable cgroup via boot commandline if not already enabled
      ansible.builtin.lineinfile:
        path: /boot/cmdline.txt
        backrefs: true
        regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
        line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    - name: Disable Swap
      ansible.builtin.command:
        cmd: "sudo dphys-swapfile swapoff && sudo dphys-swapfile uninstall && sudo systemctl disable dphys-swapfile"
    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 300  # Adjust the timeout as needed
      async: 0
      poll: 0
      register: reboot_result
    - name: Wait for the system to reboot
      ansible.builtin.async_status:
        jid: "{{ reboot_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 60
      delay: 5

