---
- name: Python Setup
  hosts: masters, workers
  become: true
  tasks:
  - name: Install required packages
    apt:
      name:
      - python3-pip
      state: present
  - name: Install Python Kubernetes client and PyYAML
    apt:
      name:
      - python3-kubernetes
      - python3-yaml
      state: present
