- name: Raspberry Pi Setup
  hosts: raspberrypi
  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - git
        - htop
    - name: Add cgroup_memory to /boot/cmdline.txt
      ansible.builtin.lineinfile:
        path: /boot/cmdline.txt
        line: "{{ lookup('file', '/boot/cmdline.txt') }} cgroup_memory=1 cgroup_enable=memory"
        backrefs: yes
    - name: Disable Swap
      ansible.builtin.command:
        cmd: "sudo dphys-swapfile swapoff && sudo dphys-swapfile uninstall && sudo systemctl disable dphys-swapfile"
      ignore_errors: yes

