---
- name: Apply Traefik Service and Ingress
  hosts: raspberry-pi
  become: true
  remote_user: root
  tasks:
  - name: Apply Traefik Service
    kubernetes.core.k8s:
      state: present
      definition: 
        apiVersion: traefik.io/v1alpha1
        kind: IngressRoute
        metadata:
          name: dashboard
          namespace: kube-system
        spec:
          entryPoints:
          - web
          routes:
          - match: Host(`traefik.mw.com`) # remenber to add <host> traefik.mw.com to /etc/hosts
            kind: Rule
            services:
            - name: api@internal
              kind: TraefikService

