---
- name: Apply Traefik Service and Ingress
  hosts: raspberry-pi
  become: true
  remote_user: root
  tasks:
  - name: Apply Traefik Service
    kubernetes.core.k8s:
      state: present
      definition: 
        apiVersion: v1
        kind: Service
        metadata:
          name: traefik-dashboard
          namespace: kube-system
          labels:
            app.kubernetes.io/instance: traefik
            app.kubernetes.io/name: traefik-dashboard
        spec:
          type: ClusterIP
          ports:
          - name: traefik
            port: 9000
            targetPort: traefik
            protocol: TCP
          selector:
            app.kubernetes.io/instance: traefik-kube-system
            app.kubernetes.io/name: traefik
  - name: Apply Traefik Ingress
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: traefik-ingress
          namespace: kube-system
          annotations:
            kubernetes.io/ingress.class: traefik
        spec:
          rules:
          - host: traefik.mw.com
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: traefik-dashboard
                    port:
                      number: 9000

