---
raspberry-pi:
  hosts:
    192.168.87.140:
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_ssh_user: matiwall


  vars:
    ansible_env:
      K8S_AUTH_KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
